language: node_js
# ensure .nvmrc exists with the node version

script:
  - yarn
  - yarn lint
  # - yarn test # enable once branch is fully converted to TS
  - yarn build

# enable once tests are in place
# after_success: "sbt coveralls"

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always
